# Generated by Django 4.0.5 on 2022-06-12 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clus_name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField()),
                ('quantity', models.IntegerField(default=1)),
                ('cluster', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstapp.cluster')),
            ],
        ),
    ]
