# Generated by Django 4.0.5 on 2022-06-13 00:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='available',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='already_booked',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='duration',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(14), django.core.validators.MinValueValidator(0)]),
        ),
    ]
