# Generated by Django 4.0.5 on 2022-06-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_cluster_available_reservation_already_booked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cluster',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
