# Generated by Django 4.0.4 on 2022-06-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Nutzer',
        ),
    ]
