# Generated by Django 4.0.5 on 2022-06-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('matrikelnummer', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
