# Generated by Django 4.0.5 on 2022-06-13 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_cluster_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
    ]
