# Generated by Django 4.0.5 on 2022-06-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_remove_reservation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='already_booked',
        ),
    ]
