# Generated by Django 4.0.5 on 2022-06-13 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_remove_reservation_already_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='user_booking',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='firstapp.nutzer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(1)]),
        ),
    ]
