# Generated by Django 4.0.5 on 2022-06-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_reservation_user_booking_reservation_user_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user_booking',
        ),
    ]
